# Generated by Django 5.2 on 2025-04-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_average_rating_review_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(verbose_name='Оценка'),
        ),
    ]
